# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    provider "aws" {
      region = "us-east-1"
      default_tags {
        tags = {
          "environment": "dev"
      "managed_by": "terraform"
      "owner": "gcavalcante"
      "project_name": "terragrunt-lab-1"
      "region": "us-east-1"
      "team": "spiritsec"
      
        }
      }
    }
    terraform {
      required_providers {
        aws = {
          source  = "hashicorp/aws"
          version = "5.12.0"
        }
      }
    }
