# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "spiritsec-terragrunt-lab-1-terraform"
    dynamodb_table = "terragrunt-terragrunt-lab-1-dev-state-lock"
    key            = "development/us-east-1/ecs-app/terraform.tfstate"
    region         = "us-east-1"
  }
}
